#!/bin/bash

# ZMART Test Wallet Setup Script
# This script helps you set up a test wallet for real blockchain E2E testing

set -e  # Exit on error

echo "🔑 ZMART Test Wallet Setup"
echo "================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if solana CLI is installed
if ! command -v solana &> /dev/null; then
    echo -e "${RED}❌ Solana CLI not found!${NC}"
    echo "Please install it: https://docs.solana.com/cli/install-solana-cli-tools"
    exit 1
fi

echo -e "${GREEN}✅ Solana CLI found${NC}"
echo ""

# Configuration
WALLET_PATH="$HOME/.config/solana/zmart-test-wallet.json"
ENV_TEST_FILE=".env.test"

echo "📍 Test wallet will be created at: $WALLET_PATH"
echo ""

# Check if wallet already exists
if [ -f "$WALLET_PATH" ]; then
    echo -e "${YELLOW}⚠️  Test wallet already exists at $WALLET_PATH${NC}"
    read -p "Do you want to use the existing wallet? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Generating new wallet..."
        rm -f "$WALLET_PATH"
        solana-keygen new --outfile "$WALLET_PATH" --no-bip39-passphrase
    else
        echo "Using existing wallet..."
    fi
else
    echo "Generating new test wallet..."
    solana-keygen new --outfile "$WALLET_PATH" --no-bip39-passphrase
fi

echo ""
echo -e "${GREEN}✅ Test wallet ready${NC}"
echo ""

# Get public key
PUBLIC_KEY=$(solana-keygen pubkey "$WALLET_PATH")
echo "📋 Public Key: $PUBLIC_KEY"
echo ""

# Get private key array
PRIVATE_KEY=$(cat "$WALLET_PATH")
echo "🔐 Private Key (as JSON array):"
echo "$PRIVATE_KEY"
echo ""

# Set Solana CLI to devnet
echo "🌐 Setting Solana CLI to devnet..."
solana config set --url devnet
echo ""

# Check current balance
echo "💰 Checking devnet SOL balance..."
BALANCE=$(solana balance "$PUBLIC_KEY" --url devnet 2>&1)
echo "Current balance: $BALANCE"
echo ""

# Offer to airdrop SOL
if [[ "$BALANCE" == *"0 SOL"* ]] || [[ "$BALANCE" == *"Error"* ]]; then
    echo -e "${YELLOW}⚠️  Wallet has no SOL${NC}"
    echo "Attempting to airdrop 2 SOL from devnet faucet..."

    # Try airdrop (may fail due to rate limits)
    if solana airdrop 2 "$PUBLIC_KEY" --url devnet; then
        echo -e "${GREEN}✅ Airdrop successful!${NC}"
        BALANCE=$(solana balance "$PUBLIC_KEY" --url devnet)
        echo "New balance: $BALANCE"
    else
        echo -e "${RED}❌ Airdrop failed (rate limit or faucet down)${NC}"
        echo ""
        echo "Please get devnet SOL manually:"
        echo "1. Visit: https://faucet.solana.com"
        echo "2. Or ask team member to send SOL to: $PUBLIC_KEY"
        echo "3. Target: 100 SOL for comprehensive testing"
    fi
fi

echo ""
echo "📝 Creating .env.test configuration..."

# Create .env.test if it doesn't exist
if [ ! -f "$ENV_TEST_FILE" ]; then
    cat > "$ENV_TEST_FILE" << EOF
# ZMART Real Blockchain E2E Testing Configuration
# Generated by setup-test-wallet.sh on $(date)
# NEVER commit this file to git!

# ==============================================================================
# TEST WALLET CONFIGURATION
# ==============================================================================
TEST_WALLET_PRIVATE_KEY='${PRIVATE_KEY}'
TEST_WALLET_PUBLIC_KEY='${PUBLIC_KEY}'

# ==============================================================================
# SOLANA CONFIGURATION
# ==============================================================================
SOLANA_CLUSTER='devnet'
SOLANA_RPC_URL='https://api.devnet.solana.com'

# ==============================================================================
# ZMART PROGRAM IDS
# ==============================================================================
ZMART_PROGRAM_ID='7h3gXfBfYFueFVLYyfL5Qo1QGsf4GQUfW96FKVgnUsJS'
TEST_MARKET_ID='HFaHHLFukTcA15khhvssYa7fTFmkzxTDsLih2LGVWCrM'

# ==============================================================================
# SUPABASE CONFIGURATION
# ==============================================================================
NEXT_PUBLIC_SUPABASE_URL='https://your-project.supabase.co'
NEXT_PUBLIC_SUPABASE_ANON_KEY='your-anon-key'

# ==============================================================================
# TEST EXECUTION SETTINGS
# ==============================================================================
BLOCKCHAIN_CONFIRMATION_TIMEOUT=60000
TRANSACTION_BUILD_TIMEOUT=10000
VERBOSE_LOGGING=true
SCREENSHOT_ON_SUCCESS=false
VIDEO_ON_SUCCESS=false
EOF

    echo -e "${GREEN}✅ Created $ENV_TEST_FILE${NC}"
    echo ""
    echo -e "${YELLOW}⚠️  Important: Update Supabase credentials in $ENV_TEST_FILE${NC}"
else
    echo -e "${YELLOW}⚠️  $ENV_TEST_FILE already exists${NC}"
    echo "Please manually update the following in $ENV_TEST_FILE:"
    echo "  TEST_WALLET_PRIVATE_KEY='$PRIVATE_KEY'"
    echo "  TEST_WALLET_PUBLIC_KEY='$PUBLIC_KEY'"
fi

echo ""
echo "================================"
echo -e "${GREEN}🎉 Test Wallet Setup Complete!${NC}"
echo "================================"
echo ""
echo "📋 Summary:"
echo "  • Wallet path: $WALLET_PATH"
echo "  • Public key: $PUBLIC_KEY"
echo "  • Balance: $BALANCE"
echo "  • Config file: $ENV_TEST_FILE"
echo ""
echo "🚀 Next Steps:"
echo "  1. Ensure you have enough devnet SOL (target: 100 SOL)"
echo "  2. Update Supabase credentials in $ENV_TEST_FILE"
echo "  3. Run tests: pnpm test:e2e:real"
echo ""
echo "💡 Tip: Keep this terminal output - you may need the public key!"
echo ""
